server:
  port: 8080
spring:
  application:
    name: user

  datasource:
    username: 'postgres'
    password: '1085'
    url: jdbc:postgresql://localhost:5433/user_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      show_sql: 'true'
